# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/home/tungxt/rosproject/src/morelab_robot_platform/msg/ADC.msg;/home/tungxt/rosproject/src/morelab_robot_platform/msg/BatteryLevel.msg;/home/tungxt/rosproject/src/morelab_robot_platform/msg/Distances.msg;/home/tungxt/rosproject/src/morelab_robot_platform/msg/DistanceWheel.msg;/home/tungxt/rosproject/src/morelab_robot_platform/msg/KeyStroke.msg;/home/tungxt/rosproject/src/morelab_robot_platform/msg/Ping.msg;/home/tungxt/rosproject/src/morelab_robot_platform/msg/Speech.msg;/home/tungxt/rosproject/src/morelab_robot_platform/msg/SpeedWheel.msg;/home/tungxt/rosproject/src/morelab_robot_platform/msg/StopSlidingSignal.msg;/home/tungxt/rosproject/src/morelab_robot_platform/msg/Velocity.msg;/home/tungxt/rosproject/src/morelab_robot_platform/msg/Voltages.msg"
services_str = "/home/tungxt/rosproject/src/morelab_robot_platform/srv/Accelerate.srv;/home/tungxt/rosproject/src/morelab_robot_platform/srv/DriveWithDistance.srv;/home/tungxt/rosproject/src/morelab_robot_platform/srv/DriveWithPower.srv;/home/tungxt/rosproject/src/morelab_robot_platform/srv/DriveWithSpeed.srv;/home/tungxt/rosproject/src/morelab_robot_platform/srv/GetDistance.srv;/home/tungxt/rosproject/src/morelab_robot_platform/srv/GetHeading.srv;/home/tungxt/rosproject/src/morelab_robot_platform/srv/GetSpeed.srv;/home/tungxt/rosproject/src/morelab_robot_platform/srv/GetStatus.srv;/home/tungxt/rosproject/src/morelab_robot_platform/srv/ResetEncoder.srv;/home/tungxt/rosproject/src/morelab_robot_platform/srv/Rotate.srv;/home/tungxt/rosproject/src/morelab_robot_platform/srv/StopAtDistance.srv"
pkg_name = "morelab_robot_platform"
dependencies_str = "sensor_msgs;geometry_msgs;roscpp;std_msgs;tf"
langs = "gencpp;genlisp;genpy"
dep_include_paths_str = "morelab_robot_platform;/home/tungxt/rosproject/src/morelab_robot_platform/msg;sensor_msgs;/opt/ros/hydro/share/sensor_msgs/cmake/../msg;geometry_msgs;/opt/ros/hydro/share/geometry_msgs/cmake/../msg;roscpp;/opt/ros/hydro/share/roscpp/cmake/../msg;std_msgs;/opt/ros/hydro/share/std_msgs/cmake/../msg;tf;/opt/ros/hydro/share/tf/cmake/../msg"
PYTHON_EXECUTABLE = "/usr/bin/python"
package_has_static_sources = '' == 'TRUE'
