/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/tungxt/rosproject/src/morelab_robot_platform/srv/GetHeading.srv
 *
 */


#ifndef MORELAB_ROBOT_PLATFORM_MESSAGE_GETHEADINGRESPONSE_H
#define MORELAB_ROBOT_PLATFORM_MESSAGE_GETHEADINGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace morelab_robot_platform
{
template <class ContainerAllocator>
struct GetHeadingResponse_
{
  typedef GetHeadingResponse_<ContainerAllocator> Type;

  GetHeadingResponse_()
    : heading(0)  {
    }
  GetHeadingResponse_(const ContainerAllocator& _alloc)
    : heading(0)  {
    }



   typedef uint16_t _heading_type;
  _heading_type heading;




  typedef boost::shared_ptr< ::morelab_robot_platform::GetHeadingResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morelab_robot_platform::GetHeadingResponse_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct GetHeadingResponse_

typedef ::morelab_robot_platform::GetHeadingResponse_<std::allocator<void> > GetHeadingResponse;

typedef boost::shared_ptr< ::morelab_robot_platform::GetHeadingResponse > GetHeadingResponsePtr;
typedef boost::shared_ptr< ::morelab_robot_platform::GetHeadingResponse const> GetHeadingResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morelab_robot_platform::GetHeadingResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morelab_robot_platform::GetHeadingResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace morelab_robot_platform

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'roscpp': ['/opt/ros/hydro/share/roscpp/cmake/../msg'], 'morelab_robot_platform': ['/home/tungxt/rosproject/src/morelab_robot_platform/msg'], 'sensor_msgs': ['/opt/ros/hydro/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg'], 'tf': ['/opt/ros/hydro/share/tf/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::morelab_robot_platform::GetHeadingResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morelab_robot_platform::GetHeadingResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morelab_robot_platform::GetHeadingResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morelab_robot_platform::GetHeadingResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morelab_robot_platform::GetHeadingResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morelab_robot_platform::GetHeadingResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morelab_robot_platform::GetHeadingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3204bea69e84bbd63420c608a176827e";
  }

  static const char* value(const ::morelab_robot_platform::GetHeadingResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3204bea69e84bbd6ULL;
  static const uint64_t static_value2 = 0x3420c608a176827eULL;
};

template<class ContainerAllocator>
struct DataType< ::morelab_robot_platform::GetHeadingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morelab_robot_platform/GetHeadingResponse";
  }

  static const char* value(const ::morelab_robot_platform::GetHeadingResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morelab_robot_platform::GetHeadingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 heading\n\
\n\
";
  }

  static const char* value(const ::morelab_robot_platform::GetHeadingResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morelab_robot_platform::GetHeadingResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.heading);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct GetHeadingResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morelab_robot_platform::GetHeadingResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morelab_robot_platform::GetHeadingResponse_<ContainerAllocator>& v)
  {
    s << indent << "heading: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.heading);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORELAB_ROBOT_PLATFORM_MESSAGE_GETHEADINGRESPONSE_H
