/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/tungxt/rosproject/src/morelab_robot_platform/srv/GetStatus.srv
 *
 */


#ifndef MORELAB_ROBOT_PLATFORM_MESSAGE_GETSTATUS_H
#define MORELAB_ROBOT_PLATFORM_MESSAGE_GETSTATUS_H

#include <ros/service_traits.h>


#include <morelab_robot_platform/GetStatusRequest.h>
#include <morelab_robot_platform/GetStatusResponse.h>


namespace morelab_robot_platform
{

struct GetStatus
{

typedef GetStatusRequest Request;
typedef GetStatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetStatus
} // namespace morelab_robot_platform


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::morelab_robot_platform::GetStatus > {
  static const char* value()
  {
    return "1d68d83766b794b474930687da7dce82";
  }

  static const char* value(const ::morelab_robot_platform::GetStatus&) { return value(); }
};

template<>
struct DataType< ::morelab_robot_platform::GetStatus > {
  static const char* value()
  {
    return "morelab_robot_platform/GetStatus";
  }

  static const char* value(const ::morelab_robot_platform::GetStatus&) { return value(); }
};


// service_traits::MD5Sum< ::morelab_robot_platform::GetStatusRequest> should match 
// service_traits::MD5Sum< ::morelab_robot_platform::GetStatus > 
template<>
struct MD5Sum< ::morelab_robot_platform::GetStatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::morelab_robot_platform::GetStatus >::value();
  }
  static const char* value(const ::morelab_robot_platform::GetStatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::morelab_robot_platform::GetStatusRequest> should match 
// service_traits::DataType< ::morelab_robot_platform::GetStatus > 
template<>
struct DataType< ::morelab_robot_platform::GetStatusRequest>
{
  static const char* value()
  {
    return DataType< ::morelab_robot_platform::GetStatus >::value();
  }
  static const char* value(const ::morelab_robot_platform::GetStatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::morelab_robot_platform::GetStatusResponse> should match 
// service_traits::MD5Sum< ::morelab_robot_platform::GetStatus > 
template<>
struct MD5Sum< ::morelab_robot_platform::GetStatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::morelab_robot_platform::GetStatus >::value();
  }
  static const char* value(const ::morelab_robot_platform::GetStatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::morelab_robot_platform::GetStatusResponse> should match 
// service_traits::DataType< ::morelab_robot_platform::GetStatus > 
template<>
struct DataType< ::morelab_robot_platform::GetStatusResponse>
{
  static const char* value()
  {
    return DataType< ::morelab_robot_platform::GetStatus >::value();
  }
  static const char* value(const ::morelab_robot_platform::GetStatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MORELAB_ROBOT_PLATFORM_MESSAGE_GETSTATUS_H
