footprint: [[0.36,0.0],[0.28,0.24],[0.0,0.36],[-0.47,0.15],[-0.47,-0.15],[0.0,-0.36],[0.28,-0.24]]

cost_factor: 0.55 #0.8
neutral_cost: 66 #50
lethal_cost: 253

transform_tolerance: 0.3
obstacle_range: 2.5 #2.5
max_obstacle_height: 3.0
min_obstacle_height: 0.0
raytrace_range: 3.0 #3.0

obstacle_layer:
  observation_sources: base_scan
  base_scan: {data_type: LaserScan, sensor_frame: base_laser_link, clearing: true, marking: true, topic: /base_scan, expected_update_rate: 20}

inflation_layer:
  inflation_radius: 0.5
  cost_scaling_factor: 3.75
