RRTDMPPlanner:
  robot_radius: 2
  goal_tolerance: 12
  path_tolerance: 30
  path_checkpoint_resolution: 1 # do not change
  obstacle_inflation_radius: 1
  time_step: 0.3
  num_step: 3
  linear_velocity_max: 1.0
  angular_velocity_max: 1.0
  linear_velocity_min: 0.25
  angular_velocity_min: 0.0
  motion_primitive_resolution: 5 # odd numbers work best
  max_iterations: 100
  controller_frequency: 10.0
  local_costmap_border: false
  forward_bias: 5
  velocity_topic: "robot_0/cmd_vel"
  rule_offset: 20.0
  goal_offset: 0.0
  person_offset: 40.0
  rule_scale: 5.0
  goal_scale: 10.0
  person_scale: 0.5
  mp_range_scale: 0.05
  stop_loops: 30
