RRTDMPPlanner:
  robot_radius: 5
  goal_tolerance: 12
  path_tolerance: 30
  path_checkpoint_resolution: 1 # do not change
  obstacle_inflation_radius: 1
  time_step: 0.25
  num_step: 7
  linear_velocity_max: 1.0
  angular_velocity_max: 1.0
  linear_velocity_min: 0.0
  angular_velocity_min: 0.0
  motion_primitive_resolution: 3 # odd numbers work best
  max_iterations: 100
  controller_frequency: 10.0
  local_costmap_border: false
  forward_bias: 5
  velocity_topic: "robot_0/cmd_vel"
  rule_offset: 5.0
  goal_offset: 0.0
  person_offset: 110.0 # the number of cells where force begins to be applied
  rule_scale: 5.0
  goal_scale: 30.0
  person_scale: 30 # 0.5
  mp_range_scale: 0.05
  stop_loops: 2
  rule_weight: 0.75
  goal_weight: 1.50
  person_weight: 0.75
  avoid_ang: 0.0
  p_dist_weight: 1.5
  p_ang_weight: 0.5
  tilt_bias: 0.785 #0.785rad is 45deg
