RRTDMPPlanner:
  robot_radius: 3
  goal_tolerance: 12
  path_tolerance: 40
  path_checkpoint_resolution: 1 # do not change
  obstacle_inflation_radius: 1
  time_step: 0.3
  num_step: 3
  linear_velocity_max: 1.0
  angular_velocity_max: 1.0
  linear_velocity_min: 0.0
  angular_velocity_min: 0.0
  motion_primitive_resolution: 3 # odd numbers work best
  max_iterations: 12
  controller_frequency: 10.0
  local_costmap_border: false
  forward_bias: 5
  velocity_topic: "robot_0/cmd_vel"
  rule_offset: 10.0
  goal_offset: -20.0
  person_offset: 80.0 # the number of cells where force begins to be applied
  rule_scale: 5.0
  goal_scale: 30.0
  person_scale: 30 # 0.5
  mp_range_scale: 0.05
  stop_loops: 3
  rule_weight: 1.3
  goal_weight: 1.1
  person_weight: 0.6
  avoid_ang: -0.2
  p_dist_weight: 1.5
  p_ang_weight: 0.5
  tilt_bias: 2.355 #0.785rad is 45deg
  linear_acceleration_max: 1.3
  angular_acceleration_max: 1.7
